name: Build Image
on: [ pull_request ]
jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: go-imap-notmuch
        tags: latest ${{ github.sha }}
        dockerfiles: |
          ./Dockerfile
